env:
  global:
    - secure: MD7BMlLXNzsFU6/DUKo6Uy9TrKmcff2UTd4gmgWIMh8YFAhLXzy+A2tAhitlkCtmzjOTyoJOS/aV9eyptv2DUcHA43NYkrYKEh9v2HLB8S7Rw++7ySpOk7+6pJT1GV1mN0XTtYvfnm+QZSryxY2738YQezIttiVKupF5sQz7TE2yraFxFhkmwdCilTWIEKhGXF3zgsIRpu7hjHWY1aDeaOS9cirrFv3Vxy0mqAAzG279REQbV0kNiQmCUTjgaAxNaP9IVeKg3oPfRcvSNTES0+HDGnRLD2ar1CSHq3nF9UEnVnM3sc21Hr0Yrfn9q12IHCkT1Z0kErGFPFKp6oElizevOkxxcBo8fGYwjccvbhx5vf6BuGC1IdfX3PkuEnkytbRYKcfR2kCHfWRwudfZqFjvt/biJO9T153cTcifk7PGKttwAEnu6odFsxSabirvMbKP4B03BGPXB7T9lSMctMO3M1jMJkCJvhKXkKkMa2vxbzlU8+NVCUmnSCkBLKYO95ADVbZYTCkAgqkwnjQBrt0y10AXsz8tnUDDJWz7OooJpy8dSh4Dj641WsrxA9cwgYMXpFTxiHC5h76HMuIwi6bzxQU8VtnCyJxX3do4hTbV+GegfvAqUvs0aHWqDO7GZOu/BXXlWc7xIMw03am2CmMHcMyO04P31PmemQS9jo4=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/Michael_Trimms_Hosts
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
