env:
  global:
    - secure: a5VYJYETqzuBdDD84lTRwcO9gZsUf//6scTvZBUTQSvBTydZn7Ebs20zE53fnXrsw7c3YJdq8Ra4g5LH+dEkuRFusSBBO8M5pD/M9H48qMhENGCYEUnA3T2ZrTpNKlFWED5l98ePRQAUu8tOJhj5mRkAcfjCjWIc4KAZtjJlUV6GfW8GLVyQS7x5ZfnWaj1S7EmMiABTW7HMMndvw++uyts+6oMEhPz0N2pIz6meuJL/endaPvAD2esOHBSoe+PDTp5c8Vc8+BTokGQRNmR5C7aq5tznKPn6TSjiSB1p5/DZRhyp0tDP1/dzNWmdj8EZATyaCfyHgqYRkZQz+GNwOsz/GzFrelV2KxxE1BnWxBy2kq/ZSTiOHOy8F2aaLwhbMECAV/I/zHQh5/+l0XiCM50EFk3uTBJZimAq/n5IzD0vEJrUxBQuq8TJ49edBcs7WJfFSRycfXNcQk2Yo3VwCsMvB3kkMAkhw3i+475vIPh0D1E1lv4DLsuRLeGjUEL5pHhMltpVhRxEHZClBeNqxNKGnl+rIzzwnIb4akLJCBv75a+trgsOJYvsWqpqJc0SAYbCY5+wMDfdMKqo+Qu8nM5+lFyKIDMSpRtRg7apaKN+pFxcoxTErI6wEAEhydjb9/29h79i4PNZ5/RW8Gp96neSagP6TRAbP36Japiaf0Y=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/Michael_Trimms_Hosts
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
