env:
  global:
    - secure: gHulWoImSbM1IVK6o6Gww5o7+GCmujQq9ujdTkkOuo0PqXD8DL/sxgyCxt/gM3UQVEb48SPKITrkoPrisyki1ZSMHK2oZxtKFzCEUJ/PbtSPdUIbFynfeBDaJSBHGH8bzjTZ9cv7IaJ9seOPYzNJ/opIz0iyPIn49926k5DK6X/6D38TsFEER4NQd3kCtr71fPaBcwnYUTFZLQR7qTFHYeQXhqr15qhfdSPLJiI95IuihwBY24Gpdeh144m8tZQ6CntUikusQXVa+Hhbje7bk45AjjQWG4Suu/bKNtfj9JeGpSZawFeYHNYWXwL5Hu5epFzLblwfE879qbK1GTPHdv93mPHWRKdRtieR0xe9VPz69ikFJ52EcuACS23XqzaffsOlx7Bb21xGNi2yi4Ae0Mgw/bCo1C4kgCKOLWVwV7sjDmzGYyQAsXqVOlfAEGLfz8cK+x5Je95L/aI6Ps7j2P+mOMm3qsHJ/2s5tSKRBIuYmvMjrAcx4WAaSR08hiO2lwJgctG9y/BbTRIrt7O23tWCQOKx3alcX3/DenTBQzusvp7Uo42ZRArkgnQItyPXYaJUK8KxHwT+itDB1RbwIi0T+NvO22oywyagFv0PdrmWKZGQD2BHOxp5J0ZMByMliG0JU6V9pM0pryQ20gKjAmgq1MlthiaJ+SrluBNi5L0=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/Michael_Trimms_Hosts
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
