env:
  global:
    - secure: fNUhlAj0503c6Hp3OijW4dPf0DCN++pCUau7UrqSNx/lWz2KaCQnGnrhMsHrxRjN6D96GWOkruAC6+JhgLCVO7bTPAuUAd0XlMJKDMI8GL+aRZTOyA6u1h4pkFAHbz6QGT+muVnure0vtEXOed7SM4/AuVf3jnWL4suVCXa/A8twFLkpYVtvG5MDQXgGbdLYJtRipKRkC4s1AsshJnQwkpi7D+cmitGuxFkNrDLBer3PTpf97Pekhg177hpHH2epI21lgQXvlxJ68kNteslQaCnTRQWOjYVrstkuDzkxfIv4pYNXchbO6t9H4Nt05JwgYOeqVu48dPxECaQkGdfpFOC+11IUPNnqgHQ3db+gNE5w2Qn9x/bSQy9nYoZ8ejo6wGb3v4lDuc3Wm629lJIBokk0E+z86oewIXxwL+Q14ZNNThU9ABtKO6kLNs4JZWp26agEYYT8/GJhEKa57iBtXxKD0cpopps201+zM4BNqqkzfLjnyo1OIaGtItH3ELsWD0wT43SviYKLVdIVR65laix5X7/Mw45NQaRpf9KVYQMiBYLjWAlZShau9Rj4afsZfPQT6qxZ4EhSdgDA5vl10drTQpg7W6J2IOV/XakrouGOHHWm4Pgb0NNDv6RhIa0FwhcqCjdYfKiLjPts3b4oBux7r9fmP64b0iJdGqy5iKo=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/Michael_Trimms_Hosts
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
